trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- bash: echo $(System.DefaultWorkingDirectory)
- bash: ls -R $(System.DefaultWorkingDirectory)
- bash: echo $(Build.ArtifactStagingDirectory)
- bash: echo $(Build.ArtifactStagingDirectory)
- bash: java -version; wheris java
- bash: where node 
- bash: python --version 
- bash: terraform --version
- bash: wheris terraform
- bash: echo $PATH 


- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)\01-currency-exchange-microservice-basic\configuration\iaac\azure\kubernetes'
    #commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctrnitinxyz'
    backendAzureRmContainerName: 'storageacctnitincontainer'
    backendAzureRmKey: 'kubernetes-dev.tfstate'

